name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy code to FTP server using SamKirkland's FTP-Deploy-Action
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ${{ secrets.FTP_HOST }}       # Your FTP server host
          username: ${{ secrets.FTP_USERNAME }} # Your FTP username
          password: ${{ secrets.FTP_PASSWORD }} # Your FTP password
          local-dir: ./                         # Local directory to upload (your project root)
          server-dir: /htdocs/SweetStream/      # Target directory on the FTP server
          protocol: ftp                         # Set FTP as the protocol
